name: marnie_pos
description: Marnie Store POS v2.1 - Flutter with offline-first Firebase sync

publish_to: 'none'
version: 2.1.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.2

  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1

  # Local offline DB
  sqflite: ^2.3.3
  path: ^1.9.0

  # Connectivity
  connectivity_plus: ^6.0.3

  # Barcode scanner
  mobile_scanner: ^5.2.3

  # UI
  google_fonts: ^6.2.1
  intl: ^0.19.0

  # Data / utils
  uuid: ^4.4.2

  # Export / share
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
